<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematron="http://download.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>agribot_bringup</name>
  <version>0.1.0</version>
  <description>Launch files, worlds, and configs for the AgriBot orchard-harvesting robot (Gazebo Sim + MoveIt 2)</description>
  <maintainer email="you@example.com">your_name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ur_simulation_gz</exec_depend>
  <exec_depend>ur_moveit_config</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_image</exec_depend>
  <exec_depend>foxglove_bridge</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>agribot_perception</exec_depend>
  <exec_depend>agribot_manipulation</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
